---
title: "project1"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(pracma)
library(lme4)
library(targets)
library(here)
library(data.table)
library(ggplot2)
```
	
# Code from Anders
## Load the data

```{r}
tar_load(c(observed_sample_data, sample_data,summary_statistics), store = here("project_1/_targets"))
```

## Compare the summary statistics

```{r}
# root mean squared error
rmse <- summary_statistics[,sqrt(mean((gold_standard-observed)^2, na.rm = TRUE)), by = c("statistic", "Number_of_BMI_measurements")]%>%
  rename(rmse = V1)  %>%
  subset(!is.na(Number_of_BMI_measurements)) 

ggplot(rmse, aes(y = rmse, x = Number_of_BMI_measurements, group = statistic)) +
  geom_point(size = 2) +  
  geom_line(color = "black", size = 1) +  # Connect points with lines
  # geom_smooth(method = "loess", color = "red", linetype = "dashed", se = FALSE) +  # Add smooth trend
  facet_wrap(~statistic, scales = "free", ncol = 5) +  
  theme_bw() +
  labs(x = "Number of BMI Measurements", y = "RMSE", title = "RMSE Trends by Statistic")+
  scale_x_discrete(breaks = seq(0, 50, by = 5))+
  theme(
    plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
    legend.position = "top",
    axis.title = element_text(size = 16, face = "bold"),
    strip.text = element_text(size = 12, face = "bold"),  # Improve facet labels readability
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) 
ggsave('rmse_trend.pdf', width = 20, height = 12, dpi = 300)
```


```{r}
rmse_table <- 
  rmse%>%
  arrange(statistic, Number_of_BMI_measurements) %>%
  pivot_wider(names_from = Number_of_BMI_measurements, values_from = rmse)

writexl::write_xlsx(rmse_table, 'rmse_table.xlsx')
```

## Plot the observed and golden standard

```{r}
summary_statistics <- 
  summary_statistics %>%
  mutate(statistic = factor(statistic,
                            levels = c("First measured BMI",  "Last measured BMI", 
                                       "AUC",  "AUC (BMI>=25)", "AUC (BMI>=30)", 
                                       "First velocity", "Total velocity", "Total variation", 
                                       "Percentage of time (BMI<25)",  "Percentage of time (BMI>=25)",  "Percentage of time (BMI>=30)", 
                                       "Coefficient of variation", 
                                       "Percentage of BMI group changes", "Percentage of relative changes>=5%",  "Percentage of relative changes>=10%"),
                            ordered = TRUE))

# Plot using ggplot2
ggplot(summary_statistics, aes(y = observed, x = gold_standard)) +
  geom_point(size = 1) +  
  facet_wrap(~statistic, scales = "free", ncol = 5) +  
  geom_abline(slope = 1, intercept = 0, color = "red", size = 1) +
  geom_smooth(method = "lm", color = "blue", size = 1) +
  labs(
    x = "gold_standard",
    y = "observed",
    title = "Comparison between the summary statistics based on True and Observed data"
  ) +
  theme_bw() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
    legend.position = "top",
    axis.title = element_text(size = 16, face = "bold"),
    strip.text = element_text(size = 12, face = "bold"),  # Improve facet labels readability
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
  ggsave("comparison of summary statistics between true and observed value.pdf", width = 20, height = 12, dpi = 300)
```


```{r}
df_plot <- subset(observed_sample_data, id %in% c(1:100))
unique_ids <- unique(df_plot$id)
n_ids <- length(unique_ids)
n_pages <- ceiling(n_ids / 20)

pdf("observed_individual_trajectory.pdf", width = 20, height = 12)

for (i in 1:n_pages) {
  p <- ggplot(df_plot, aes(x = age, y = bmi)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(limits = c(40, 65)) +
    ggforce::facet_wrap_paginate(~ id, ncol = 5, nrow = 4) +
    theme_bw() +
    theme(text = element_text(size = 18)) +
    labs(title = "BMI", x = "Age", y = "BMI")
  print(p)
}
dev.off()
```

## Plot the interval
```{r}
colnames(summary_statistics)
df_plot <- subset(summary_statistics, Number_of_BMI_measurements == 2)
```

